sudo: false
language: c
python:
  - "2.4"
compiler:
  - gcc
  - clang
cache: ccache
addons:
  apt:
    packages:
      - libaio-dev
      - libattr1-dev
      - libbrlapi-dev
      - libcap-ng-dev
      - libgnutls-dev
      - libgtk-3-dev
      - libiscsi-dev
      - liblttng-ust-dev
      - libncurses5-dev
      - libnss3-dev
      - libpixman-1-dev
      - libpng12-dev
      - librados-dev
      - libsdl1.2-dev
      - libseccomp-dev
      - libspice-protocol-dev
      - libspice-server-dev
      - libssh2-1-dev
      - liburcu-dev
      - libusb-1.0-0-dev
      - libvte-2.90-dev
      - sparse
      - uuid-dev

notifications:
  irc:
    channels:
      - "irc.oftc.net#qemu"
    on_success: change
    on_failure: always
env:
  global:
    - TEST_CMD="make check"
    - EXTRA_CONFIG=""
  matrix:
    # Group major targets together with their linux-user counterparts
    - TARGETS=alpha-softmmu,alpha-linux-user,cris-softmmu,cris-linux-user,m68k-softmmu,m68k-linux-user,microblaze-softmmu,microblazeel-softmmu,microblaze-linux-user,microblazeel-linux-user
    - TARGETS=arm-softmmu,arm-linux-user,armeb-linux-user,aarch64-softmmu,aarch64-linux-user
    - TARGETS=i386-softmmu,i386-linux-user,x86_64-softmmu,x86_64-linux-user
    - TARGETS=mips-softmmu,mips64-softmmu,mips64el-softmmu,mipsel-softmmu,mips-linux-user,mips64-linux-user,mips64el-linux-user,mipsel-linux-user,mipsn32-linux-user,mipsn32el-linux-user
    - TARGETS=or32-softmmu,or32-linux-user,ppc-softmmu,ppc64-softmmu,ppcemb-softmmu,ppc-linux-user,ppc64-linux-user,ppc64abi32-linux-user,ppc64le-linux-user
    - TARGETS=s390x-softmmu,s390x-linux-user,sh4-softmmu,sh4eb-softmmu,sh4-linux-user,sh4eb-linux-user,sparc-softmmu,sparc64-softmmu,sparc-linux-user,sparc32plus-linux-user,sparc64-linux-user,unicore32-softmmu,unicore32-linux-user
    # Group remaining softmmu only targets into one build
    - TARGETS=lm32-softmmu,moxie-softmmu,tricore-softmmu,xtensa-softmmu,xtensaeb-softmmu
git:
  # we want to do this ourselves
  submodules: false
before_install:
  - wget -O - http://people.linaro.org/~alex.bennee/qemu-submodule-git-seed.tar.xz | tar -xvJ
  - git submodule update --init --recursive
before_script:
  - ./configure --target-list=${TARGETS} --enable-debug-tcg ${EXTRA_CONFIG}
script:
  - make -j2 && ${TEST_CMD}
matrix:
  # We manually include a number of additional build for non-standard bits
  include:
    # Debug related options
    - env: TARGETS=x86_64-softmmu
           EXTRA_CONFIG="--enable-debug"
      compiler: gcc
    # We currently disable "make check"
    - env: TARGETS=alpha-softmmu
           EXTRA_CONFIG="--enable-debug --enable-tcg-interpreter"
           TEST_CMD=""
      compiler: gcc
    # Disable a few of the optional features
    - env: TARGETS=x86_64-softmmu
           EXTRA_CONFIG="--disable-linux-aio --disable-cap-ng --disable-attr --disable-brlapi --disable-uuid --disable-libusb"
      compiler: gcc
    # Currently configure doesn't force --disable-pie
    - env: TARGETS=x86_64-softmmu
           EXTRA_CONFIG="--enable-gprof --enable-gcov --disable-pie"
      compiler: gcc
    # Sparse
    - env: TARGETS=x86_64-softmmu
           EXTRA_CONFIG="--enable-sparse"
      compiler: gcc
    # Modules
    - env: TARGETS=arm-softmmu,x86_64-softmmu
           EXTRA_CONFIG="--enable-modules"
      compiler: gcc
    # All the trace backends (apart from dtrace)
    - env: TARGETS=i386-softmmu
           EXTRA_CONFIG="--enable-trace-backends=log"
      compiler: gcc
    # We currently disable "make check" (until 41fc57e44ed regression fixed)
    - env: TARGETS=x86_64-softmmu
           EXTRA_CONFIG="--enable-trace-backends=simple"
           TEST_CMD=""
      compiler: gcc
    # We currently disable "make check"
    - env: TARGETS=x86_64-softmmu
           EXTRA_CONFIG="--enable-trace-backends=ftrace"
           TEST_CMD=""
      compiler: gcc
    # We currently disable "make check"
    - env: TARGETS=x86_64-softmmu
           EXTRA_CONFIG="--enable-trace-backends=ust"
           TEST_CMD=""
      compiler: gcc
    # All the co-routine backends (apart from windows)
    # We currently disable "make check"
    - env: TARGETS=x86_64-softmmu
           EXTRA_CONFIG="--with-coroutine=gthread"
           TEST_CMD=""
      compiler: gcc
    - env: TARGETS=x86_64-softmmu
           EXTRA_CONFIG="--with-coroutine=ucontext"
      compiler: gcc
    - env: TARGETS=x86_64-softmmu
           EXTRA_CONFIG="--with-coroutine=sigaltstack"
      compiler: gcc
